// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BlobCreateOption is an autogenerated mock type for the BlobCreateOption type
type BlobCreateOption struct {
	mock.Mock
}

// Apply provides a mock function with given fields: _a0
func (_m *BlobCreateOption) Apply(_a0 interface{}) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBlobCreateOption creates a new instance of BlobCreateOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlobCreateOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlobCreateOption {
	mock := &BlobCreateOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
