// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	distribution "github.com/distribution/distribution/v3"
	mock "github.com/stretchr/testify/mock"
)

// BlobIngester is an autogenerated mock type for the BlobIngester type
type BlobIngester struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, options
func (_m *BlobIngester) Create(ctx context.Context, options ...distribution.BlobCreateOption) (distribution.BlobWriter, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 distribution.BlobWriter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...distribution.BlobCreateOption) (distribution.BlobWriter, error)); ok {
		return rf(ctx, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...distribution.BlobCreateOption) distribution.BlobWriter); ok {
		r0 = rf(ctx, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(distribution.BlobWriter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...distribution.BlobCreateOption) error); ok {
		r1 = rf(ctx, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Put provides a mock function with given fields: ctx, mediaType, p
func (_m *BlobIngester) Put(ctx context.Context, mediaType string, p []byte) (distribution.Descriptor, error) {
	ret := _m.Called(ctx, mediaType, p)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 distribution.Descriptor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (distribution.Descriptor, error)); ok {
		return rf(ctx, mediaType, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) distribution.Descriptor); ok {
		r0 = rf(ctx, mediaType, p)
	} else {
		r0 = ret.Get(0).(distribution.Descriptor)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, mediaType, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Resume provides a mock function with given fields: ctx, id
func (_m *BlobIngester) Resume(ctx context.Context, id string) (distribution.BlobWriter, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 distribution.BlobWriter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (distribution.BlobWriter, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) distribution.BlobWriter); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(distribution.BlobWriter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBlobIngester creates a new instance of BlobIngester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlobIngester(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlobIngester {
	mock := &BlobIngester{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
