// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	digest "github.com/opencontainers/go-digest"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// BlobProvider is an autogenerated mock type for the BlobProvider type
type BlobProvider struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, dgst
func (_m *BlobProvider) Get(ctx context.Context, dgst digest.Digest) ([]byte, error) {
	ret := _m.Called(ctx, dgst)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, digest.Digest) ([]byte, error)); ok {
		return rf(ctx, dgst)
	}
	if rf, ok := ret.Get(0).(func(context.Context, digest.Digest) []byte); ok {
		r0 = rf(ctx, dgst)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, digest.Digest) error); ok {
		r1 = rf(ctx, dgst)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Open provides a mock function with given fields: ctx, dgst
func (_m *BlobProvider) Open(ctx context.Context, dgst digest.Digest) (io.ReadSeekCloser, error) {
	ret := _m.Called(ctx, dgst)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 io.ReadSeekCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, digest.Digest) (io.ReadSeekCloser, error)); ok {
		return rf(ctx, dgst)
	}
	if rf, ok := ret.Get(0).(func(context.Context, digest.Digest) io.ReadSeekCloser); ok {
		r0 = rf(ctx, dgst)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadSeekCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, digest.Digest) error); ok {
		r1 = rf(ctx, dgst)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBlobProvider creates a new instance of BlobProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlobProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlobProvider {
	mock := &BlobProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
