// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	errcode "github.com/distribution/distribution/v3/registry/api/errcode"
	mock "github.com/stretchr/testify/mock"
)

// ErrorCoder is an autogenerated mock type for the ErrorCoder type
type ErrorCoder struct {
	mock.Mock
}

// ErrorCode provides a mock function with given fields:
func (_m *ErrorCoder) ErrorCode() errcode.ErrorCode {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ErrorCode")
	}

	var r0 errcode.ErrorCode
	if rf, ok := ret.Get(0).(func() errcode.ErrorCode); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(errcode.ErrorCode)
	}

	return r0
}

// NewErrorCoder creates a new instance of ErrorCoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrorCoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *ErrorCoder {
	mock := &ErrorCoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
