// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Registry is an autogenerated mock type for the Registry type
type Registry struct {
	mock.Mock
}

// Repositories provides a mock function with given fields: ctx, repos, last
func (_m *Registry) Repositories(ctx context.Context, repos []string, last string) (int, error) {
	ret := _m.Called(ctx, repos, last)

	if len(ret) == 0 {
		panic("no return value specified for Repositories")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) (int, error)); ok {
		return rf(ctx, repos, last)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) int); ok {
		r0 = rf(ctx, repos, last)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, string) error); ok {
		r1 = rf(ctx, repos, last)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRegistry creates a new instance of Registry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *Registry {
	mock := &Registry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
