// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// RequestModifier is an autogenerated mock type for the RequestModifier type
type RequestModifier struct {
	mock.Mock
}

// ModifyRequest provides a mock function with given fields: _a0
func (_m *RequestModifier) ModifyRequest(_a0 *http.Request) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ModifyRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*http.Request) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRequestModifier creates a new instance of RequestModifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequestModifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *RequestModifier {
	mock := &RequestModifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
