// Code generated by mockery v2.43.0. DO NOT EDIT.

package credentials

import mock "github.com/stretchr/testify/mock"

// MockCredentialSource is an autogenerated mock type for the CredentialSource type
type MockCredentialSource struct {
	mock.Mock
}

// FetchCredentials provides a mock function with given fields: registry
func (_m *MockCredentialSource) FetchCredentials(registry string) (*Credential, error) {
	ret := _m.Called(registry)

	if len(ret) == 0 {
		panic("no return value specified for FetchCredentials")
	}

	var r0 *Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*Credential, error)); ok {
		return rf(registry)
	}
	if rf, ok := ret.Get(0).(func(string) *Credential); ok {
		r0 = rf(registry)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Credential)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(registry)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockCredentialSource creates a new instance of MockCredentialSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialSource {
	mock := &MockCredentialSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
